name: Waka Readme

on:
  schedule:
    - cron: '0 14 * * 2,4,6'  # Runs at 12 a.m. AEST on Wednesday, Friday, and Sunday
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TIMEZONE: "True"
          SHOW_PROJECTS: "False"
          SHOW_OS: "True"
          SHOW_LANGUAGE: "True"
