name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - "master"
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: # Update permissions to grant access to repositories
      contents: read
      security-events: write
      issues: write
      pull-requests: write
      # ... add any other necessary permissions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
