name: GitHub-Profile-Summary-Cards

on:
  create:
  schedule: # execute every Monday at 12:00 UTC
    - cron: "00 12 * * mon"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
        with:
          USERNAME: ${{ github.breezy-codes }}
